// apps/low-code/react/src/pages/editor/header/index.tsx
import React from 'react'
import PropTypes from 'prop-types'
import { Link } from 'react-router-dom'

const EditorHeader = (props) => {
  return (
    <div className="h-[32px] w-full flex">
      <div className="w-[100px] pl-[6px] flex flex-row items-center">
        <div className="hover:text-blue-500">
          <Link to={'/'}>{'<'}返回</Link>
        </div>
      </div>
      <div className="flex-1 text-center">编辑器页面 id: {props.id}</div>
      <div className="w-[100px] pr-[6px] flex flex-row items-center justify-end">
        <div className="hover:text-blue-500">
          <button>保存</button>
        </div>
      </div>
    </div>
  )
}
EditorHeader.propTypes = {
  id: PropTypes.string.isRequired
}

export default EditorHeader

// apps/low-code/src/views/editor/header/index.vue
<script setup>
const props = defineProps({
  id: {
    type: String,
    default: ''
  }
})
</script>

<template>
  <div class="h-[32px] w-full flex">
    <div class="w-[100px] pl-[6px] flex flex-row items-center">
      <div><<router-link :to="{ name: 'pageList' }">返回</router-link></div>
    </div>
    <div class="flex-1 text-center">编辑器页面 id: {{ props.id }}</div>
    <div class="w-[100px] pr-[6px] flex flex-row items-center justify-end">
      <div><button>保存</button></div>
    </div>
  </div>
</template>
