// apps/low-code/src/views/editor/index.vue
<script setup>
import { useRoute } from 'vue-router'
import EditorHeader from './header'
const route = useRoute()
</script>

<template>
  <div class="h-full w-full flex flex-col">
    <div class="flex-none">
      <EditorHeader :id="route.params.id" />
    </div>
    <div class="flex-1 overflow-hidden flex">
      <div></div>
      <div>main</div>
      <div></div>
    </div>
  </div>
</template>

// apps/low-code/react/src/pages/editor/index.tsx
// import React from 'react'
import { useParams } from 'react-router-dom'
import { EventProvider } from '@/hooks/useEvent'

import EditorHeader from './header'
import EditorMain from './main'

const Editor = () => {
  const { id } = useParams<{ id: string }>()
  return (
    <EventProvider>
      <div className="h-full w-full flex flex-col">
        {/* header */}
        <div className="flex-none">
          <EditorHeader id={id} />
        </div>
        {/* main */}
        <div className="flex-1 overflow-hidden">
          <EditorMain />
        </div>
      </div>
    </EventProvider>
  )
}

export default Editor
