// apps/low-code/vue/src/control-components/title-text/index.vue
<script setup></script>
<script>
import TextIcon from '../icons/text.svg'
import { defineComponent } from 'vue'
export default defineComponent({
  name: 'TitleText'
})
export const config = {
  id: 'title-text',
  icon: TextIcon,
  componentName: '标题文本1',
  limit: 50
}
</script>
<template>
  <div>这是一个title-text组件</div>
</template>

// apps/low-code/react/src/elements/title-text/index.tsx
import React from 'react'
import PropTypes from 'prop-types'
import Icon from './icon.svg'
const ElementInputText = (props) => {
  return <div>这是一个title-text组件</div>
}

ElementInputText.propTypes = {}

export const config = {
  id: 'title-text',
  name: '标题文本',
  icon: Icon,
  limit: 50,
  // label: 'Text',
  component: ElementInputText
}
export default ElementInputText
