// apps/bingo/client/src/pages/Home.tsx
import React from 'react'
import { Link } from 'react-router-dom'

function Home() {
  return (
    <div>
      <div>Home</div>
      <div className="mt-4 flex">
        <Link to="/paper">
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            生成游戏纸
          </button>
        </Link>
      </div>
    </div>
  )
}

export default Home

// demo/animation/src/views/Home.vue
<script setup>
import { useRouter } from 'vue-router'
const router = useRouter()

const routes = router.options.routes.filter((v) => v.path != '/')
</script>

<template>
  <div class="flex">
    <template v-for="route in routes" :key="route.path">
      <div class="p-2">
        <button
          class="p-2 rounded-md bg-blue-500 text-white"
          @click="$router.push(route.path)"
        >
          {{ route.meta ? route.meta.title : route.name }}
        </button>
      </div>
    </template>
  </div>
</template>
