// apps/low-code/react/src/pages/editor/main/settings/index.tsx
import React, { useContext } from 'react'

import { EditorContext } from '../../EditorContext'

const Settings = () => {
  const { id } = useContext(EditorContext)

  return (
    <div className="w-full h-full flex flex-col">
      <div className="flex-none h-[30px] leading-[30px] bg-gray-800 text-gray-400 text-center">
        配置区 {id}
      </div>
      <div className="flex-1 p-[10px] overflow-hidden bg-gray-200 text-gray-800">
        <div>配置1</div>
        <div>配置2</div>
        <div>配置3</div>
        <div>配置4</div>
      </div>
    </div>
  )
}

// Settings.propTypes = {}

export default Settings

// apps/low-code/vue/src/views/editor/settings/index.vue
<script setup>
import useStore from '@/store/editor'
import { storeToRefs } from 'pinia'
const store = useStore()

const { currentControl } = storeToRefs(store)
</script>

<template>
  <div class="w-full h-full flex flex-col">
    <div
      class="flex-none h-[30px] items-center px-2 bg-gray-700 text-gray-400 text-center"
    >
      配置区
    </div>
    <div class="overflow-auto flex-1">
      {{ currentControl }}
      <!-- <div v-for="i in 100" :key="i">{{ i }}</div> -->
    </div>
  </div>
</template>
